export const stations = [
    'Airport',
    'Arts Center',
    'Ashby',
    'Avondale',
    'Bankhead',
    'Brookhaven / Oglethorpe',
    'Buckhead',
    'Chamblee',
    'Civic Center',
    'College Park',
    'Dome / GWCC / Philips Arena / CNN Center',
    'Doraville',
    'Dunwoody',
    'East Lake',
    'East Point',
    'Edgewood / Candler Park',
    'Five Points',
    'Garnett',
    'Georgia State',
    'Hamilton E. Holmes',
    'Indian Creek',
    'Inman Park / Reynoldstown',
    'Kensington',
    'King Memorial',
    'Lakewood / Ft. McPherson',
    'Lenox',
    'Lindbergh Center',
    'Medical Center',
    'Midtown',
    'North Ave',
    'North Springs',
    'Oakland City',
    'Peachtree Center',
    'Sandy Springs',
    'Vine City',
    'West End',
    'West Lake',
];

export const quickIncidentCategories = [
    'Vandalism/Graffiti',
    'Light Issue',
    'Sign Outage',
    'Train Delayed/Stopped',
    'Nuisance Behavior',
];

export const otherIncidentCategories = [
    'Assualt or fighting',
    'Gun / knife / shooting',
    'Human Trafficking',
    'Medical emergency',
    'Panhandle/Homeless',
    'Person needs assistance',
    'Sanitary issue',
    'Suspicious Activity',
    'Unattended bag or package',
    'Other issue',
];

export const incidentStatus = {
    0: '',
    1: 'Seen by MARTA',
    2: 'MARTA Resolving'
};